In [2]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
import pandas as pd
import numpy as np
import re

In [13]:
def web_extraction():
    movie_names = []
    release_date = []
    description = []
    directors = []
    movie_stars = []
    ratings = []
    duration = []
    genre = []

    #url = 'https://www.imdb.com/list/ls009668711/';
    url = 'https://www.imdb.com/list/ls009668711/?sort=moviemeter,asc&st_dt=&mode=detail&page=1'
    pth = 'chromedriver.exe'

    driver = webdriver.Chrome(pth)

    driver.get(url)
    
    sleep(20)

    movies = 100
    for i in range(1,movies+1):
        
        movie = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/a')
                                    
        release = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/span[2]')

                                                 
        desc = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[2]')
                                                
        dire = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[3]/a[1]')

        rat = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/div[1]/div[1]/span[2]')

        dura = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[3]')

        gen = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[5]')
                                            
        movie_ = movie.text
        movie_names.append(movie_)
        
        whole = driver.find_element_by_xpath(f'/html/body/div[3]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[3]')
        whole_ = whole.text
        director, space, stars = whole_.partition('Stars: ')
        movie_stars.append(stars)
    
    
        release_ = release.text
        find_wo_brackets = release_.replace('(','')
        find_wo_brackets = find_wo_brackets.replace(')','')

        if i == 10:
            find_wo_brackets = 2004
        if i == 38:
            find_wo_brackets = 2015
        if i == 84:
            find_wo_brackets = 2006
        release_date.append(int(find_wo_brackets))

        description_ = desc.text
        description.append(description_)

        directors_ = dire.text
        directors.append(directors_)

        ratings_ = rat.text
        int_ratings_ = float(ratings_)
        ratings.append(int_ratings_)

        duration_ = dura.text
        durat, space, stri = duration_.partition(' ')
        int_duration = int(durat)
        duration.append(int_duration)

        genres_ = gen.text
        genre.append(genres_)

#########################################       SAVING IT INTO PANDAS DATAFRAME        #######################################################################
  
    data = {'Movies':movie_names,'Description':description,'Directors':directors,'Movie Stars':movie_stars,'Genre':genre,'Release Date':release_date,'Duration (in mins)':duration,'Ratings':ratings}
    
    
    
    labels = pd.RangeIndex(start=1,stop=movies+1,step=1)
    
    df = pd.DataFrame(data,index =labels).rename_axis('Serial Number',axis=1)
    df.to_csv('drama_imdb.csv')
    
    return df

web_extraction()

Serial Number,Movies,Description,Directors,Movie Stars,Genre,Release Date,Duration (in mins),Ratings
1,The Godfather,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...","Crime, Drama",1972,175,9.2
2,The Godfather: Part II,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...","Crime, Drama",1974,202,9.0
3,The Dark Knight,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...","Action, Crime, Drama",2008,152,9.0
4,Pulp Fiction,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"John Travolta, Uma Thurman, Samuel L. Jackson,...","Crime, Drama",1994,154,8.9
5,Heat,A group of high-end professional thieves start...,Michael Mann,"Al Pacino, Robert De Niro, Val Kilmer, Jon Voight","Action, Crime, Drama",1995,170,8.2
...,...,...,...,...,...,...,...,...
96,La La Land,"While navigating their careers in Los Angeles,...",Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....","Comedy, Drama, Music",2016,128,8.0
97,A Clockwork Orange,"In the future, a sadistic gang leader is impri...",Stanley Kubrick,"Malcolm McDowell, Patrick Magee, Michael Bates...","Crime, Sci-Fi",1971,136,8.3
98,The Shape of Water,At a top secret research facility in the 1960s...,Guillermo del Toro,"Sally Hawkins, Octavia Spencer, Michael Shanno...","Drama, Fantasy, Romance",2017,123,7.3
99,JFK,New Orleans District Attorney Jim Garrison dis...,Oliver Stone,"Kevin Costner, Gary Oldman, Jack Lemmon, Walte...","Drama, History, Thriller",1991,189,8.0
100,Prisoners,When Keller Dover's daughter and her friend go...,Denis Villeneuve,"Hugh Jackman, Jake Gyllenhaal, Viola Davis, Me...","Crime, Drama, Mystery",2013,153,8.1

In [3]:
df_new = pd.read_csv('drama_imdb.csv',index_col=0)
df_new

,Movies,Description,Directors,Movie Stars,Genre,Release Date,Duration (in mins),Ratings
Serial Number,,,,,,,,
1,Once Upon a Time... In Hollywood,A faded television actor and his stunt double ...,Quentin Tarantino,"Leonardo DiCaprio, Brad Pitt, Margot Robbie, E...","Comedy, Drama",2019,161,7.6
2,The Shawshank Redemption,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Drama,1994,142,9.3
3,The Dark Knight,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...","Action, Crime, Drama",2008,152,9.0
4,The Godfather,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...","Crime, Drama",1972,175,9.2
5,Fight Club,An insomniac office worker and a devil-may-car...,David Fincher,"Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier",Drama,1999,139,8.8
...,...,...,...,...,...,...,...,...
96,A Very Long Engagement,Tells the story of a young woman's relentless ...,Jean-Pierre Jeunet,"Audrey Tautou, Gaspard Ulliel, Jodie Foster, D...","Drama, Mystery, Romance",2004,133,7.6
97,Children of Heaven,"After a boy loses his sister's pair of shoes, ...",Majid Majidi,"Mohammad Amir Naji, Amir Farrokh Hashemian, Ba...","Drama, Family, Sport",1997,89,8.3
98,The Legend of 1900,"A baby boy, discovered in 1900 on an ocean lin...",Giuseppe Tornatore,"Tim Roth, Pruitt Taylor Vince, MÃ©lanie Thierry...","Drama, Music, Romance",1998,169,8.1
99,1900,The epic tale of a class struggle in twentieth...,Bernardo Bertolucci,"Robert De Niro, GÃ©rard Depardieu, Dominique Sa...","Drama, History",1976,317,7.7
100,Stalag 17,After two Americans are killed while escaping ...,Billy Wilder,"William Holden, Don Taylor, Otto Preminger, Ro...","Comedy, Drama, War",1953,116,8.0

In [4]:
df_new.sort_values(by='Release Date',ascending=True)

,Movies,Description,Directors,Movie Stars,Genre,Release Date,Duration (in mins),Ratings
Serial Number,,,,,,,,
68,Gone with the Wind,The manipulative daughter of a Georgia plantat...,Victor Fleming,"Clark Gable, Vivien Leigh, Thomas Mitchell, Ba...","Drama, History, Romance",1939,238,8.1
78,Citizen Kane,Following the death of publishing tycoon Charl...,Orson Welles,"Orson Welles, Joseph Cotten, Dorothy Comingore...","Drama, Mystery",1941,119,8.3
59,Casablanca,A cynical expatriate American cafe owner strug...,Michael Curtiz,"Humphrey Bogart, Ingrid Bergman, Paul Henreid,...","Drama, Romance, War",1942,102,8.5
100,Stalag 17,After two Americans are killed while escaping ...,Billy Wilder,"William Holden, Don Taylor, Otto Preminger, Ro...","Comedy, Drama, War",1953,116,8.0
92,On the Waterfront,An ex-prize fighter turned New Jersey longshor...,Elia Kazan,"Marlon Brando, Karl Malden, Lee J. Cobb, Rod S...","Crime, Drama, Thriller",1954,108,8.1
...,...,...,...,...,...,...,...,...
55,La La Land,"While navigating their careers in Los Angeles,...",Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....","Comedy, Drama, Music",2016,128,8.0
38,The Shape of Water,At a top secret research facility in the 1960s...,Guillermo del Toro,"Sally Hawkins, Octavia Spencer, Michael Shanno...","Drama, Fantasy, Romance",2017,123,7.3
63,"Three Billboards Outside Ebbing, Missouri",A mother personally challenges the local autho...,Martin McDonagh,"Frances McDormand, Woody Harrelson, Sam Rockwe...","Comedy, Crime, Drama",2017,115,8.1
47,Green Book,A working-class Italian-American bouncer becom...,Peter Farrelly,"Viggo Mortensen, Mahershala Ali, Linda Cardell...","Biography, Comedy, Drama",2018,130,8.2
1,Once Upon a Time... In Hollywood,A faded television actor and his stunt double ...,Quentin Tarantino,"Leonardo DiCaprio, Brad Pitt, Margot Robbie, E...","Comedy, Drama",2019,161,7.6

In [32]:
import matplotlib.pyplot as plt